### ISSUE TITLE
pipibibis Nudity switch mask error

### ISSUE THREAD

**Issue by hgage2003** [Coin-OpCollection/Distribution-OpenFPGA#2]
Hi, it is not possible to enable nudity switch in pipibibis on pocket.
mask for it in interact json must be FFF7FFFF

**Comment by atrac17** [comment]
0xFEFFFF XOR the 0x0008 is FFF7FFFF. Thanks! It may be on by default, not sure if that's how I had the MRA setup when the ROM is generated.

![image](https://github.com/Coin-OpCollection/Distribution-OpenFPGA/assets/32810066/a39c2fcb-31e7-4d38-b549-39dad93d2e2c)
