### ISSUE TITLE
technos_gfx_repack.py (Unfamilarity Issue)

### ISSUE THREAD

**Issue by AnotherPocket** [Coin-OpCollection/Distribution-OpenFPGA#3]
Hello,
As I understand it, the technos_gfx_repack.py script must be run on the ROM before using the MRA tool. However, I've hit a rather difficult wall as I am unsure how to run this script on Windows 11. My research has led me to believe that I must install Python on my machine, however, this is not something I can do.  Is there another tool or method for repacking the graphics before converting with the MRA tool?

Thank you!

**Comment by davewongillies** [comment]
[Use one of the various Pocket updaters](https://github.com/Coin-OpCollection/Distribution-OpenFPGA?tab=readme-ov-file#beta-access--pocket-updater) to get the ROMs:

* pupdate: https://mattpannella.github.io/pupdate/
* Pocket Sync: https://github.com/neil-morrison44/pocket-sync
* Pocket Updater: https://github.com/RetroDriven/Pocket_Updater

**Comment by AnotherPocket** [comment]
Thank you for that suggestion! I have hand built my mSD card, organized it, and altered many default aspects for my own personal needs (removed files, edited data.json, custom. .bin images, etc). I've been informed that the 'updaters' will overwrite some of my changes, because of that information I do not use them. 

Is there perhaps a different solution?

**Comment by AnotherPocket** [comment]
Hi. Thank you for your suggestion. I set up my mSD card manually, editing files and organizing for my specific needs. I was operating under the impression that the 'updater' programs would overwrite my directory structure. However, Pocket Updater allowed me to update locally and select exactly what I wanted. Cheers.
