### ISSUE TITLE
Problem with The Combatribes (US, Rev 2, Set 1).mra

### ISSUE THREAD

**Issue by megane72GH** [Coin-OpCollection/Distribution-OpenFPGA#4]
Cannot find 

<part name="28j17-0.105" crc="d7978eeb" map="01"/>

in any known mame rom latest or older, maybe it's my fault.....

part not found in zip: 28j17-0.105 (d7978eeb)

checked also on 
http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=ctribe

**Comment by AnotherPocket** [comment]
I also can not find a Combatribes that contains the flie 28j17-0.105. It's absent from Arcade Italia list. I checked some MAME DATs as well and couldn't find reference to that file. Google "combatribes 28j17-0.104" or "ctribe 28j17-0.104" and get many results. Google "combatribes 28j17-0.105" or "ctribe 28j17-0.105" and get 0 results.

**Comment by atrac17** [comment]
This has been covered on Patreon, it is a blank file with no contents used to complete banking and deflate the ROMs properly. I've attached the file, place it in the respective zip folder you use to compile the ROM file.

[28j17-0.zip](https://github.com/user-attachments/files/18222623/28j17-0.zip)
