### ISSUE TITLE
yunit & zunit combined zips causing users to install more cores than they expect

### ISSUE THREAD

**Issue by neil-morrison44** [Coin-OpCollection/Distribution-OpenFPGA#5]
Hi
Was just clicking around in Pocket Sync and noticed that a few cores that are listed as individual cores within the inventory (and thus the updaters) come from the same zip in this repo (this is me when I click to install Mortal Kombat):
<img width="1172" alt="Screenshot 2024-12-30 at 22 33 14" src="https://github.com/user-attachments/assets/1e6f74b8-8ab0-4946-8110-7156070e8df1" />

Ideally, so that people get what they expect on install / update each core should be its own zip - particularly when there's a lot of cores in one zip like yunit

**Comment by atrac17** [comment]
It's great that Pocket Sync supports distribution, but the official updater that's supported is [pupdate](https://github.com/Coin-OpCollection/Distribution-OpenFPGA?tab=readme-ov-file#beta-access--pocket-updater). pupdate will install the cores individually from the same zip in this repo. I've tried to reach out a few times to work on integrating support with Pocket Sync. Feel free to message me on discord.

![image](https://github.com/user-attachments/assets/b1566369-27e0-4c46-af97-ebb68cfe6c40)

**Comment by davewongillies** [comment]
> It's great that Pocket Sync supports distribution, but the official updater that's supported is [pupdate](https://github.com/Coin-OpCollection/Distribution-OpenFPGA?tab=readme-ov-file#beta-access--pocket-updater). pupdate will install the cores individually from the same zip in this repo. I've tried to reach out a few times to work on integrating support with Pocket Sync. Feel free to message me on discord.
> 
> ![image](https://private-user-images.githubusercontent.com/32810066/399387494-b1566369-27e0-4c46-af97-ebb68cfe6c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NzAzMDEsIm5iZiI6MTczNTY3MDAwMSwicGF0aCI6Ii8zMjgxMDA2Ni8zOTkzODc0OTQtYjE1NjYzNjktMjdlMC00YzQ2LWFmOTctZWJiNjhjZmU2YzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDE4MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiYjgxNDRkYTdiYTA5YTYxN2M5ZDU2MGJiYWMyZWNmMGFjNzA4YzgyMWFlMjE1YzdlZDkxZTMyNjkxMzVhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.crr0m5-msoXvtGGFHmb-e19hXsP8AvxPf_1vCq64WpA)

Pupdate & Pocket Sync use the same HTTP API to download cores via the [OpenFPGA cores inventory](https://openfpga-cores-inventory.github.io/analogue-pocket/) so this problem effects pupdate as well.

**Comment by neil-morrison44** [comment]
Yeah - it’s just less noticeable in pupdate since most people probably install everything at once & there isn’t immediate UI showing that more cores than expected have installed.

I _think_ pupdate might try to install / update the same zip once for every core in it.

I’m putting extra UI into Pocket Sync to make it clearer when a zip has more than one core & allow the user to mass-deselect the files per core….. but that just helps the 1st time install & they’ll all come in if any of the cores in the bundle get an update.


If it’s something we have to deal with long term it might make sense for the inventory to break the zip up & self host it, but that’ll be prone to missing files & would break download counts for cores released via GitHub releases. There’s probably an argument to be made for having the inventory just reject any core added where the zip has more than one core in it.

**Comment by atrac17** [comment]
I'm not separating them until they are out of beta. Whether I was informed properly or not regarding the distribution method is irrelevant. 

Midway should be updated every release as the binary changes and has been in constant development. We've spoken privately on this already.
